// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/feed-relay/localdir/internal/fs"
)

// FeedMock is a mock implementation of provider.Feed.
//
//	func TestSomethingThatUsesFeed(t *testing.T) {
//
//		// make and configure a mocked provider.Feed
//		mockedFeed := &FeedMock{
//			AudioFilesFunc: func() []fs.AudioFile {
//				panic("mock out the AudioFiles method")
//			},
//			DescriptionFunc: func() string {
//				panic("mock out the Description method")
//			},
//			DirFunc: func() string {
//				panic("mock out the Dir method")
//			},
//			ImageFunc: func() string {
//				panic("mock out the Image method")
//			},
//			LimitFunc: func() int {
//				panic("mock out the Limit method")
//			},
//			LinkFunc: func() string {
//				panic("mock out the Link method")
//			},
//			SetFinderFunc: func(finder *fs.Finder)  {
//				panic("mock out the SetFinder method")
//			},
//			ShowsFunc: func() []string {
//				panic("mock out the Shows method")
//			},
//			SlugFunc: func() string {
//				panic("mock out the Slug method")
//			},
//			TitleFunc: func() string {
//				panic("mock out the Title method")
//			},
//		}
//
//		// use mockedFeed in code that requires provider.Feed
//		// and then make assertions.
//
//	}
type FeedMock struct {
	// AudioFilesFunc mocks the AudioFiles method.
	AudioFilesFunc func() []fs.AudioFile

	// DescriptionFunc mocks the Description method.
	DescriptionFunc func() string

	// DirFunc mocks the Dir method.
	DirFunc func() string

	// ImageFunc mocks the Image method.
	ImageFunc func() string

	// LimitFunc mocks the Limit method.
	LimitFunc func() int

	// LinkFunc mocks the Link method.
	LinkFunc func() string

	// SetFinderFunc mocks the SetFinder method.
	SetFinderFunc func(finder *fs.Finder)

	// ShowsFunc mocks the Shows method.
	ShowsFunc func() []string

	// SlugFunc mocks the Slug method.
	SlugFunc func() string

	// TitleFunc mocks the Title method.
	TitleFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// AudioFiles holds details about calls to the AudioFiles method.
		AudioFiles []struct {
		}
		// Description holds details about calls to the Description method.
		Description []struct {
		}
		// Dir holds details about calls to the Dir method.
		Dir []struct {
		}
		// Image holds details about calls to the Image method.
		Image []struct {
		}
		// Limit holds details about calls to the Limit method.
		Limit []struct {
		}
		// Link holds details about calls to the Link method.
		Link []struct {
		}
		// SetFinder holds details about calls to the SetFinder method.
		SetFinder []struct {
			// Finder is the finder argument value.
			Finder *fs.Finder
		}
		// Shows holds details about calls to the Shows method.
		Shows []struct {
		}
		// Slug holds details about calls to the Slug method.
		Slug []struct {
		}
		// Title holds details about calls to the Title method.
		Title []struct {
		}
	}
	lockAudioFiles  sync.RWMutex
	lockDescription sync.RWMutex
	lockDir         sync.RWMutex
	lockImage       sync.RWMutex
	lockLimit       sync.RWMutex
	lockLink        sync.RWMutex
	lockSetFinder   sync.RWMutex
	lockShows       sync.RWMutex
	lockSlug        sync.RWMutex
	lockTitle       sync.RWMutex
}

// AudioFiles calls AudioFilesFunc.
func (mock *FeedMock) AudioFiles() []fs.AudioFile {
	if mock.AudioFilesFunc == nil {
		panic("FeedMock.AudioFilesFunc: method is nil but Feed.AudioFiles was just called")
	}
	callInfo := struct {
	}{}
	mock.lockAudioFiles.Lock()
	mock.calls.AudioFiles = append(mock.calls.AudioFiles, callInfo)
	mock.lockAudioFiles.Unlock()
	return mock.AudioFilesFunc()
}

// AudioFilesCalls gets all the calls that were made to AudioFiles.
// Check the length with:
//
//	len(mockedFeed.AudioFilesCalls())
func (mock *FeedMock) AudioFilesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAudioFiles.RLock()
	calls = mock.calls.AudioFiles
	mock.lockAudioFiles.RUnlock()
	return calls
}

// ResetAudioFilesCalls reset all the calls that were made to AudioFiles.
func (mock *FeedMock) ResetAudioFilesCalls() {
	mock.lockAudioFiles.Lock()
	mock.calls.AudioFiles = nil
	mock.lockAudioFiles.Unlock()
}

// Description calls DescriptionFunc.
func (mock *FeedMock) Description() string {
	if mock.DescriptionFunc == nil {
		panic("FeedMock.DescriptionFunc: method is nil but Feed.Description was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDescription.Lock()
	mock.calls.Description = append(mock.calls.Description, callInfo)
	mock.lockDescription.Unlock()
	return mock.DescriptionFunc()
}

// DescriptionCalls gets all the calls that were made to Description.
// Check the length with:
//
//	len(mockedFeed.DescriptionCalls())
func (mock *FeedMock) DescriptionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDescription.RLock()
	calls = mock.calls.Description
	mock.lockDescription.RUnlock()
	return calls
}

// ResetDescriptionCalls reset all the calls that were made to Description.
func (mock *FeedMock) ResetDescriptionCalls() {
	mock.lockDescription.Lock()
	mock.calls.Description = nil
	mock.lockDescription.Unlock()
}

// Dir calls DirFunc.
func (mock *FeedMock) Dir() string {
	if mock.DirFunc == nil {
		panic("FeedMock.DirFunc: method is nil but Feed.Dir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDir.Lock()
	mock.calls.Dir = append(mock.calls.Dir, callInfo)
	mock.lockDir.Unlock()
	return mock.DirFunc()
}

// DirCalls gets all the calls that were made to Dir.
// Check the length with:
//
//	len(mockedFeed.DirCalls())
func (mock *FeedMock) DirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDir.RLock()
	calls = mock.calls.Dir
	mock.lockDir.RUnlock()
	return calls
}

// ResetDirCalls reset all the calls that were made to Dir.
func (mock *FeedMock) ResetDirCalls() {
	mock.lockDir.Lock()
	mock.calls.Dir = nil
	mock.lockDir.Unlock()
}

// Image calls ImageFunc.
func (mock *FeedMock) Image() string {
	if mock.ImageFunc == nil {
		panic("FeedMock.ImageFunc: method is nil but Feed.Image was just called")
	}
	callInfo := struct {
	}{}
	mock.lockImage.Lock()
	mock.calls.Image = append(mock.calls.Image, callInfo)
	mock.lockImage.Unlock()
	return mock.ImageFunc()
}

// ImageCalls gets all the calls that were made to Image.
// Check the length with:
//
//	len(mockedFeed.ImageCalls())
func (mock *FeedMock) ImageCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockImage.RLock()
	calls = mock.calls.Image
	mock.lockImage.RUnlock()
	return calls
}

// ResetImageCalls reset all the calls that were made to Image.
func (mock *FeedMock) ResetImageCalls() {
	mock.lockImage.Lock()
	mock.calls.Image = nil
	mock.lockImage.Unlock()
}

// Limit calls LimitFunc.
func (mock *FeedMock) Limit() int {
	if mock.LimitFunc == nil {
		panic("FeedMock.LimitFunc: method is nil but Feed.Limit was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLimit.Lock()
	mock.calls.Limit = append(mock.calls.Limit, callInfo)
	mock.lockLimit.Unlock()
	return mock.LimitFunc()
}

// LimitCalls gets all the calls that were made to Limit.
// Check the length with:
//
//	len(mockedFeed.LimitCalls())
func (mock *FeedMock) LimitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLimit.RLock()
	calls = mock.calls.Limit
	mock.lockLimit.RUnlock()
	return calls
}

// ResetLimitCalls reset all the calls that were made to Limit.
func (mock *FeedMock) ResetLimitCalls() {
	mock.lockLimit.Lock()
	mock.calls.Limit = nil
	mock.lockLimit.Unlock()
}

// Link calls LinkFunc.
func (mock *FeedMock) Link() string {
	if mock.LinkFunc == nil {
		panic("FeedMock.LinkFunc: method is nil but Feed.Link was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLink.Lock()
	mock.calls.Link = append(mock.calls.Link, callInfo)
	mock.lockLink.Unlock()
	return mock.LinkFunc()
}

// LinkCalls gets all the calls that were made to Link.
// Check the length with:
//
//	len(mockedFeed.LinkCalls())
func (mock *FeedMock) LinkCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLink.RLock()
	calls = mock.calls.Link
	mock.lockLink.RUnlock()
	return calls
}

// ResetLinkCalls reset all the calls that were made to Link.
func (mock *FeedMock) ResetLinkCalls() {
	mock.lockLink.Lock()
	mock.calls.Link = nil
	mock.lockLink.Unlock()
}

// SetFinder calls SetFinderFunc.
func (mock *FeedMock) SetFinder(finder *fs.Finder) {
	if mock.SetFinderFunc == nil {
		panic("FeedMock.SetFinderFunc: method is nil but Feed.SetFinder was just called")
	}
	callInfo := struct {
		Finder *fs.Finder
	}{
		Finder: finder,
	}
	mock.lockSetFinder.Lock()
	mock.calls.SetFinder = append(mock.calls.SetFinder, callInfo)
	mock.lockSetFinder.Unlock()
	mock.SetFinderFunc(finder)
}

// SetFinderCalls gets all the calls that were made to SetFinder.
// Check the length with:
//
//	len(mockedFeed.SetFinderCalls())
func (mock *FeedMock) SetFinderCalls() []struct {
	Finder *fs.Finder
} {
	var calls []struct {
		Finder *fs.Finder
	}
	mock.lockSetFinder.RLock()
	calls = mock.calls.SetFinder
	mock.lockSetFinder.RUnlock()
	return calls
}

// ResetSetFinderCalls reset all the calls that were made to SetFinder.
func (mock *FeedMock) ResetSetFinderCalls() {
	mock.lockSetFinder.Lock()
	mock.calls.SetFinder = nil
	mock.lockSetFinder.Unlock()
}

// Shows calls ShowsFunc.
func (mock *FeedMock) Shows() []string {
	if mock.ShowsFunc == nil {
		panic("FeedMock.ShowsFunc: method is nil but Feed.Shows was just called")
	}
	callInfo := struct {
	}{}
	mock.lockShows.Lock()
	mock.calls.Shows = append(mock.calls.Shows, callInfo)
	mock.lockShows.Unlock()
	return mock.ShowsFunc()
}

// ShowsCalls gets all the calls that were made to Shows.
// Check the length with:
//
//	len(mockedFeed.ShowsCalls())
func (mock *FeedMock) ShowsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockShows.RLock()
	calls = mock.calls.Shows
	mock.lockShows.RUnlock()
	return calls
}

// ResetShowsCalls reset all the calls that were made to Shows.
func (mock *FeedMock) ResetShowsCalls() {
	mock.lockShows.Lock()
	mock.calls.Shows = nil
	mock.lockShows.Unlock()
}

// Slug calls SlugFunc.
func (mock *FeedMock) Slug() string {
	if mock.SlugFunc == nil {
		panic("FeedMock.SlugFunc: method is nil but Feed.Slug was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSlug.Lock()
	mock.calls.Slug = append(mock.calls.Slug, callInfo)
	mock.lockSlug.Unlock()
	return mock.SlugFunc()
}

// SlugCalls gets all the calls that were made to Slug.
// Check the length with:
//
//	len(mockedFeed.SlugCalls())
func (mock *FeedMock) SlugCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSlug.RLock()
	calls = mock.calls.Slug
	mock.lockSlug.RUnlock()
	return calls
}

// ResetSlugCalls reset all the calls that were made to Slug.
func (mock *FeedMock) ResetSlugCalls() {
	mock.lockSlug.Lock()
	mock.calls.Slug = nil
	mock.lockSlug.Unlock()
}

// Title calls TitleFunc.
func (mock *FeedMock) Title() string {
	if mock.TitleFunc == nil {
		panic("FeedMock.TitleFunc: method is nil but Feed.Title was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTitle.Lock()
	mock.calls.Title = append(mock.calls.Title, callInfo)
	mock.lockTitle.Unlock()
	return mock.TitleFunc()
}

// TitleCalls gets all the calls that were made to Title.
// Check the length with:
//
//	len(mockedFeed.TitleCalls())
func (mock *FeedMock) TitleCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTitle.RLock()
	calls = mock.calls.Title
	mock.lockTitle.RUnlock()
	return calls
}

// ResetTitleCalls reset all the calls that were made to Title.
func (mock *FeedMock) ResetTitleCalls() {
	mock.lockTitle.Lock()
	mock.calls.Title = nil
	mock.lockTitle.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *FeedMock) ResetCalls() {
	mock.lockAudioFiles.Lock()
	mock.calls.AudioFiles = nil
	mock.lockAudioFiles.Unlock()

	mock.lockDescription.Lock()
	mock.calls.Description = nil
	mock.lockDescription.Unlock()

	mock.lockDir.Lock()
	mock.calls.Dir = nil
	mock.lockDir.Unlock()

	mock.lockImage.Lock()
	mock.calls.Image = nil
	mock.lockImage.Unlock()

	mock.lockLimit.Lock()
	mock.calls.Limit = nil
	mock.lockLimit.Unlock()

	mock.lockLink.Lock()
	mock.calls.Link = nil
	mock.lockLink.Unlock()

	mock.lockSetFinder.Lock()
	mock.calls.SetFinder = nil
	mock.lockSetFinder.Unlock()

	mock.lockShows.Lock()
	mock.calls.Shows = nil
	mock.lockShows.Unlock()

	mock.lockSlug.Lock()
	mock.calls.Slug = nil
	mock.lockSlug.Unlock()

	mock.lockTitle.Lock()
	mock.calls.Title = nil
	mock.lockTitle.Unlock()
}
