// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// AudioMetadataMock is a mock implementation of media.AudioMetadata.
//
//	func TestSomethingThatUsesAudioMetadata(t *testing.T) {
//
//		// make and configure a mocked media.AudioMetadata
//		mockedAudioMetadata := &AudioMetadataMock{
//			AlbumArtistFunc: func() string {
//				panic("mock out the AlbumArtist method")
//			},
//			ArtistFunc: func() string {
//				panic("mock out the Artist method")
//			},
//			CommentFunc: func() string {
//				panic("mock out the Comment method")
//			},
//			TitleFunc: func() string {
//				panic("mock out the Title method")
//			},
//		}
//
//		// use mockedAudioMetadata in code that requires media.AudioMetadata
//		// and then make assertions.
//
//	}
type AudioMetadataMock struct {
	// AlbumArtistFunc mocks the AlbumArtist method.
	AlbumArtistFunc func() string

	// ArtistFunc mocks the Artist method.
	ArtistFunc func() string

	// CommentFunc mocks the Comment method.
	CommentFunc func() string

	// TitleFunc mocks the Title method.
	TitleFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// AlbumArtist holds details about calls to the AlbumArtist method.
		AlbumArtist []struct {
		}
		// Artist holds details about calls to the Artist method.
		Artist []struct {
		}
		// Comment holds details about calls to the Comment method.
		Comment []struct {
		}
		// Title holds details about calls to the Title method.
		Title []struct {
		}
	}
	lockAlbumArtist sync.RWMutex
	lockArtist      sync.RWMutex
	lockComment     sync.RWMutex
	lockTitle       sync.RWMutex
}

// AlbumArtist calls AlbumArtistFunc.
func (mock *AudioMetadataMock) AlbumArtist() string {
	if mock.AlbumArtistFunc == nil {
		panic("AudioMetadataMock.AlbumArtistFunc: method is nil but AudioMetadata.AlbumArtist was just called")
	}
	callInfo := struct {
	}{}
	mock.lockAlbumArtist.Lock()
	mock.calls.AlbumArtist = append(mock.calls.AlbumArtist, callInfo)
	mock.lockAlbumArtist.Unlock()
	return mock.AlbumArtistFunc()
}

// AlbumArtistCalls gets all the calls that were made to AlbumArtist.
// Check the length with:
//
//	len(mockedAudioMetadata.AlbumArtistCalls())
func (mock *AudioMetadataMock) AlbumArtistCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAlbumArtist.RLock()
	calls = mock.calls.AlbumArtist
	mock.lockAlbumArtist.RUnlock()
	return calls
}

// ResetAlbumArtistCalls reset all the calls that were made to AlbumArtist.
func (mock *AudioMetadataMock) ResetAlbumArtistCalls() {
	mock.lockAlbumArtist.Lock()
	mock.calls.AlbumArtist = nil
	mock.lockAlbumArtist.Unlock()
}

// Artist calls ArtistFunc.
func (mock *AudioMetadataMock) Artist() string {
	if mock.ArtistFunc == nil {
		panic("AudioMetadataMock.ArtistFunc: method is nil but AudioMetadata.Artist was just called")
	}
	callInfo := struct {
	}{}
	mock.lockArtist.Lock()
	mock.calls.Artist = append(mock.calls.Artist, callInfo)
	mock.lockArtist.Unlock()
	return mock.ArtistFunc()
}

// ArtistCalls gets all the calls that were made to Artist.
// Check the length with:
//
//	len(mockedAudioMetadata.ArtistCalls())
func (mock *AudioMetadataMock) ArtistCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockArtist.RLock()
	calls = mock.calls.Artist
	mock.lockArtist.RUnlock()
	return calls
}

// ResetArtistCalls reset all the calls that were made to Artist.
func (mock *AudioMetadataMock) ResetArtistCalls() {
	mock.lockArtist.Lock()
	mock.calls.Artist = nil
	mock.lockArtist.Unlock()
}

// Comment calls CommentFunc.
func (mock *AudioMetadataMock) Comment() string {
	if mock.CommentFunc == nil {
		panic("AudioMetadataMock.CommentFunc: method is nil but AudioMetadata.Comment was just called")
	}
	callInfo := struct {
	}{}
	mock.lockComment.Lock()
	mock.calls.Comment = append(mock.calls.Comment, callInfo)
	mock.lockComment.Unlock()
	return mock.CommentFunc()
}

// CommentCalls gets all the calls that were made to Comment.
// Check the length with:
//
//	len(mockedAudioMetadata.CommentCalls())
func (mock *AudioMetadataMock) CommentCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockComment.RLock()
	calls = mock.calls.Comment
	mock.lockComment.RUnlock()
	return calls
}

// ResetCommentCalls reset all the calls that were made to Comment.
func (mock *AudioMetadataMock) ResetCommentCalls() {
	mock.lockComment.Lock()
	mock.calls.Comment = nil
	mock.lockComment.Unlock()
}

// Title calls TitleFunc.
func (mock *AudioMetadataMock) Title() string {
	if mock.TitleFunc == nil {
		panic("AudioMetadataMock.TitleFunc: method is nil but AudioMetadata.Title was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTitle.Lock()
	mock.calls.Title = append(mock.calls.Title, callInfo)
	mock.lockTitle.Unlock()
	return mock.TitleFunc()
}

// TitleCalls gets all the calls that were made to Title.
// Check the length with:
//
//	len(mockedAudioMetadata.TitleCalls())
func (mock *AudioMetadataMock) TitleCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTitle.RLock()
	calls = mock.calls.Title
	mock.lockTitle.RUnlock()
	return calls
}

// ResetTitleCalls reset all the calls that were made to Title.
func (mock *AudioMetadataMock) ResetTitleCalls() {
	mock.lockTitle.Lock()
	mock.calls.Title = nil
	mock.lockTitle.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *AudioMetadataMock) ResetCalls() {
	mock.lockAlbumArtist.Lock()
	mock.calls.AlbumArtist = nil
	mock.lockAlbumArtist.Unlock()

	mock.lockArtist.Lock()
	mock.calls.Artist = nil
	mock.lockArtist.Unlock()

	mock.lockComment.Lock()
	mock.calls.Comment = nil
	mock.lockComment.Unlock()

	mock.lockTitle.Lock()
	mock.calls.Title = nil
	mock.lockTitle.Unlock()
}
