// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// CommandRunnerMock is a mock implementation of media.CommandRunner.
//
//	func TestSomethingThatUsesCommandRunner(t *testing.T) {
//
//		// make and configure a mocked media.CommandRunner
//		mockedCommandRunner := &CommandRunnerMock{
//			RunFunc: func(ctx context.Context, name string, args ...string) ([]byte, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedCommandRunner in code that requires media.CommandRunner
//		// and then make assertions.
//
//	}
type CommandRunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, name string, args ...string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *CommandRunnerMock) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	if mock.RunFunc == nil {
		panic("CommandRunnerMock.RunFunc: method is nil but CommandRunner.Run was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Args []string
	}{
		Ctx:  ctx,
		Name: name,
		Args: args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, name, args...)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedCommandRunner.RunCalls())
func (mock *CommandRunnerMock) RunCalls() []struct {
	Ctx  context.Context
	Name string
	Args []string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Args []string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// ResetRunCalls reset all the calls that were made to Run.
func (mock *CommandRunnerMock) ResetRunCalls() {
	mock.lockRun.Lock()
	mock.calls.Run = nil
	mock.lockRun.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *CommandRunnerMock) ResetCalls() {
	mock.lockRun.Lock()
	mock.calls.Run = nil
	mock.lockRun.Unlock()
}
