// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"time"
)

// DurationReaderMock is a mock implementation of media.DurationReader.
//
//	func TestSomethingThatUsesDurationReader(t *testing.T) {
//
//		// make and configure a mocked media.DurationReader
//		mockedDurationReader := &DurationReaderMock{
//			DurationFunc: func(ctx context.Context, path string) (time.Duration, error) {
//				panic("mock out the Duration method")
//			},
//		}
//
//		// use mockedDurationReader in code that requires media.DurationReader
//		// and then make assertions.
//
//	}
type DurationReaderMock struct {
	// DurationFunc mocks the Duration method.
	DurationFunc func(ctx context.Context, path string) (time.Duration, error)

	// calls tracks calls to the methods.
	calls struct {
		// Duration holds details about calls to the Duration method.
		Duration []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
	}
	lockDuration sync.RWMutex
}

// Duration calls DurationFunc.
func (mock *DurationReaderMock) Duration(ctx context.Context, path string) (time.Duration, error) {
	if mock.DurationFunc == nil {
		panic("DurationReaderMock.DurationFunc: method is nil but DurationReader.Duration was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockDuration.Lock()
	mock.calls.Duration = append(mock.calls.Duration, callInfo)
	mock.lockDuration.Unlock()
	return mock.DurationFunc(ctx, path)
}

// DurationCalls gets all the calls that were made to Duration.
// Check the length with:
//
//	len(mockedDurationReader.DurationCalls())
func (mock *DurationReaderMock) DurationCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockDuration.RLock()
	calls = mock.calls.Duration
	mock.lockDuration.RUnlock()
	return calls
}

// ResetDurationCalls reset all the calls that were made to Duration.
func (mock *DurationReaderMock) ResetDurationCalls() {
	mock.lockDuration.Lock()
	mock.calls.Duration = nil
	mock.lockDuration.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *DurationReaderMock) ResetCalls() {
	mock.lockDuration.Lock()
	mock.calls.Duration = nil
	mock.lockDuration.Unlock()
}
