// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// DurationReaderMock is a mock implementation of media.DurationReader.
//
//	func TestSomethingThatUsesDurationReader(t *testing.T) {
//
//		// make and configure a mocked media.DurationReader
//		mockedDurationReader := &DurationReaderMock{
//			ReadFunc: func(path string) (int64, error) {
//				panic("mock out the Read method")
//			},
//		}
//
//		// use mockedDurationReader in code that requires media.DurationReader
//		// and then make assertions.
//
//	}
type DurationReaderMock struct {
	// ReadFunc mocks the Read method.
	ReadFunc func(path string) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// Read holds details about calls to the Read method.
		Read []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockRead sync.RWMutex
}

// Read calls ReadFunc.
func (mock *DurationReaderMock) Read(path string) (int64, error) {
	if mock.ReadFunc == nil {
		panic("DurationReaderMock.ReadFunc: method is nil but DurationReader.Read was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(path)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedDurationReader.ReadCalls())
func (mock *DurationReaderMock) ReadCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// ResetReadCalls reset all the calls that were made to Read.
func (mock *DurationReaderMock) ResetReadCalls() {
	mock.lockRead.Lock()
	mock.calls.Read = nil
	mock.lockRead.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *DurationReaderMock) ResetCalls() {
	mock.lockRead.Lock()
	mock.calls.Read = nil
	mock.lockRead.Unlock()
}
