// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/dhowden/tag"
)

// MetadataReaderMock is a mock implementation of media.MetadataReader.
//
//	func TestSomethingThatUsesMetadataReader(t *testing.T) {
//
//		// make and configure a mocked media.MetadataReader
//		mockedMetadataReader := &MetadataReaderMock{
//			MetadataFunc: func(path string) (tag.Metadata, error) {
//				panic("mock out the Metadata method")
//			},
//		}
//
//		// use mockedMetadataReader in code that requires media.MetadataReader
//		// and then make assertions.
//
//	}
type MetadataReaderMock struct {
	// MetadataFunc mocks the Metadata method.
	MetadataFunc func(path string) (tag.Metadata, error)

	// calls tracks calls to the methods.
	calls struct {
		// Metadata holds details about calls to the Metadata method.
		Metadata []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockMetadata sync.RWMutex
}

// Metadata calls MetadataFunc.
func (mock *MetadataReaderMock) Metadata(path string) (tag.Metadata, error) {
	if mock.MetadataFunc == nil {
		panic("MetadataReaderMock.MetadataFunc: method is nil but MetadataReader.Metadata was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockMetadata.Lock()
	mock.calls.Metadata = append(mock.calls.Metadata, callInfo)
	mock.lockMetadata.Unlock()
	return mock.MetadataFunc(path)
}

// MetadataCalls gets all the calls that were made to Metadata.
// Check the length with:
//
//	len(mockedMetadataReader.MetadataCalls())
func (mock *MetadataReaderMock) MetadataCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockMetadata.RLock()
	calls = mock.calls.Metadata
	mock.lockMetadata.RUnlock()
	return calls
}

// ResetMetadataCalls reset all the calls that were made to Metadata.
func (mock *MetadataReaderMock) ResetMetadataCalls() {
	mock.lockMetadata.Lock()
	mock.calls.Metadata = nil
	mock.lockMetadata.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *MetadataReaderMock) ResetCalls() {
	mock.lockMetadata.Lock()
	mock.calls.Metadata = nil
	mock.lockMetadata.Unlock()
}
