// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/feed-relay/localdir/internal/media"
)

// MetadataReaderMock is a mock implementation of media.MetadataReader.
//
//	func TestSomethingThatUsesMetadataReader(t *testing.T) {
//
//		// make and configure a mocked media.MetadataReader
//		mockedMetadataReader := &MetadataReaderMock{
//			ReadFunc: func(path string) (media.AudioMetadata, error) {
//				panic("mock out the Read method")
//			},
//		}
//
//		// use mockedMetadataReader in code that requires media.MetadataReader
//		// and then make assertions.
//
//	}
type MetadataReaderMock struct {
	// ReadFunc mocks the Read method.
	ReadFunc func(path string) (media.AudioMetadata, error)

	// calls tracks calls to the methods.
	calls struct {
		// Read holds details about calls to the Read method.
		Read []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockRead sync.RWMutex
}

// Read calls ReadFunc.
func (mock *MetadataReaderMock) Read(path string) (media.AudioMetadata, error) {
	if mock.ReadFunc == nil {
		panic("MetadataReaderMock.ReadFunc: method is nil but MetadataReader.Read was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(path)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedMetadataReader.ReadCalls())
func (mock *MetadataReaderMock) ReadCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// ResetReadCalls reset all the calls that were made to Read.
func (mock *MetadataReaderMock) ResetReadCalls() {
	mock.lockRead.Lock()
	mock.calls.Read = nil
	mock.lockRead.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *MetadataReaderMock) ResetCalls() {
	mock.lockRead.Lock()
	mock.calls.Read = nil
	mock.lockRead.Unlock()
}
